# ansible-playbook ./userget.yml -e user_name=super123
- name: Get User Parameters
  connection: local
  hosts: wti_pdu

  vars_prompt:
  - name: "user_name"
    prompt: "Enter Username"
    private: no

  tasks:
  - set_fact: use_https=True
    when: use_https is undefined
  - set_fact: validate_certs=True
    when: validate_certs is undefined

  - name: run Get User Parameters
#   no_log: true
    cpm_user:
      cpm_action: "getuser"
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
      user_name: "{{user_name}}"  # pass as -e user_name=sammy on the commandline
      use_https: "{{use_https}}"
      validate_certs: false
    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout.data }}"
