---
# ansible-playbook ./useredit.yml -e user_name=superABC -e user_pass=notime
- name: Edit Existing User
  hosts: wti_pdu
  connection: local
  gather_facts: false

  vars_prompt:
  - name: "user_name"
    prompt: "Enter Username"
    private: no
  - name: "user_pass"
    prompt: "Enter Password"

  tasks:
    - set_fact: use_https=True
      when: use_https is undefined
    - set_fact: validate_certs=True
      when: validate_certs is undefined

    - name: run Edit Existing User
#     no_log: true
      cpm_user:
        cpm_action: "edituser"
        cpm_url: "{{ansible_host}}"
        cpm_username: "{{ansible_user}}"
        cpm_password: "{{ansible_pw}}"
        user_name: "{{user_name}}"  # pass as -e user_name=sammy on the commandline
        user_pass: "{{user_pass}}"  # pass as -e user_pass=sammy on the commandline
#       user_accesslevel: 1
        use_https: "{{use_https}}"
        validate_certs: false

      register: testout
    - name: dump test output
      debug:
        msg: "{{ testout['data'] }}"
