# ansible-playbook ./plugget.yml
- name: Get Plug Parameters
  connection: local
  hosts: wti_pdu
  tasks:
  - set_fact: use_https=True
    when: use_https is undefined
  - set_fact: validate_certs=True
    when: validate_certs is undefined

  - name: run Get Plug Parameters
#   no_log: true
    cpm_plugconfig:
      cpm_action: "getplugconfig"
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
#      plug_id: "ALL"
      plug_id: "2"
      use_https: "{{use_https}}"
      validate_certs: "{{validate_certs}}"

    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout['data'] }}"
