---
# ansible-playbook ./plugset.yml
- name: Set Plug States
  hosts: wti_pdu
  connection: local
  gather_facts: false

  tasks:
    - set_fact: use_https=True
      when: use_https is undefined
    - set_fact: validate_certs=True
      when: validate_certs is undefined

    - name: run Set Plug States
      cpm_plugconfig:
        cpm_action: "setplugconfig"
        cpm_url: "{{ansible_host}}"
        cpm_username: "{{ansible_user}}"
        cpm_password: "{{ansible_pw}}"
        plug_id: "2"  # plug 2 are being changed
        plug_name: "plugname2"
        plug_bootdelay: 1
        plug_default: 0
        plug_bootpriority: 99
        use_https: "{{use_https}}"
        validate_certs: "{{validate_certs}}"

      register: testout
    - name: dump test output
      debug:
        msg: "{{ testout }}"
