# ansible-playbook ./portsedit.yml
- name: Set Port Parameters
  hosts: wti_pdu
  connection: local
  gather_facts: False

  tasks:
  - set_fact: use_https=True
    when: use_https is undefined
  - set_fact: validate_certs=True
    when: validate_certs is undefined

  - name: run Set Port Parameters of Port 7
    cpm_ports:
      cpm_action: "setport"
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
      serial_port: 7
      serial_baud: 3
      serial_portname: "Sam"
      serial_handshake: 0
      serial_stopbits: 1
      serial_parity: 0
      serial_mode: 1
      serial_cmd: 0
      serial_seq: 1
      serial_tout: 0
      serial_echo: 0
      serial_break: 0
      serial_logoff: "^X"
      use_https: "{{use_https}}"
      validate_certs: "{{validate_certs}}"

    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout['data'] }}"
