# ansible-playbook ./portsget.yml
- name: Get Port Parameters
  connection: local
  hosts: wti_pdu
  tasks:
  - set_fact: use_https=True
    when: use_https is undefined
  - set_fact: validate_certs=True
    when: validate_certs is undefined

  - name: run Get Port Parameters
#   no_log: true
    cpm_ports:
      cpm_action: "getport"
      cpm_url: "{{ansible_host}}"
      cpm_username: "{{ansible_user}}"
      cpm_password: "{{ansible_pw}}"
      serial_port: "1,2"
      use_https: "{{use_https}}"
      validate_certs: "{{validate_certs}}"

    register: testout
  - name: dump test output
    debug:
      msg: "{{ testout['data'] }}"
