---
# ansible-playbook ./getverlookup.yml
- name: Get Device Power numbers
  connection: local
  hosts: wti_pdu
  gather_facts: False

  tasks:
  - set_fact: use_https=True
    when: use_https is undefined
  - set_fact: validate_certs=True
    when: validate_certs is undefined

  - name: run Get Device Power numbers
#    no_log: true
#    startdate: "07-10-2018"
#    enddate: "07-18-2018"
    debug: msg="{{ lookup('cpm_power',
                    'getcurrent',
                    validate_certs=validate_certs,
                    use_https=use_https,
                    cpm_url=ansible_host,
                    cpm_username=ansible_user,
                    cpm_password=ansible_pw) }}"
